services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: yii2_docker_app
    volumes:
      - .:/var/www/html
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
        - "host.docker.internal:host-gateway"
    env_file: .env
    depends_on:
      - mysql_db
      - pg_db

  nginx:
    image: nginx:alpine
    container_name: yii2_docker_nginx
    ports:
      - "8080:80"
      - "8081:81"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  mysql_db:
    image: mysql:8.0
    container_name: yii2_docker_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    volumes:
      - ./docker/mysql_data:/var/lib/mysql

  pg_db:
    image: postgres:15-alpine
    container_name: yii2_docker_postgres
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_DB_USER}
      POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
    volumes:
      - ./docker/pg_data:/var/lib/postgresql/data

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: yii2_docker_phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql_db

  redis:
    image: redis:alpine
    container_name: yii2_docker_redis

  memcached:
    image: memcached:alpine
    container_name: yii2_docker_memcached